CREATE TRIGGER friendship_guard BEFORE INSERT ON friendships BEGIN
 SELECT CASE WHEN NEW.a>=NEW.b OR NOT (NEW.a<>NEW.b
 AND EXISTS(SELECT 1 FROM profiles p JOIN profiles q ON p.scope=q.scope JOIN clique_settings cs ON cs.owner=p.id JOIN clique_settings ct ON ct.owner=q.id WHERE p.id=NEW.a AND q.id=NEW.b AND cs.enabled=1 AND ct.enabled=1 AND p.paused=0 AND q.paused=0)
 AND NOT EXISTS(SELECT 1 FROM blocks k WHERE (k.sender=NEW.a AND k.recipient=NEW.b) OR (k.sender=NEW.b AND k.recipient=NEW.a))) THEN RAISE(ABORT,'Friend profile unavailable') END;
 SELECT CASE WHEN (SELECT count(*) FROM friendships fc WHERE fc.a=NEW.a OR fc.b=NEW.a)>=4 OR (SELECT count(*) FROM friendships fc WHERE fc.a=NEW.b OR fc.b=NEW.b)>=4 THEN RAISE(ABORT,'A clique can contain four friends') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM friend_likes WHERE sender=NEW.a AND recipient=NEW.b) OR NOT EXISTS(SELECT 1 FROM friend_likes WHERE sender=NEW.b AND recipient=NEW.a) THEN RAISE(ABORT,'Mutual friendship interest required') END;
END;
--> statement-breakpoint
CREATE TRIGGER friendship_immutable BEFORE UPDATE ON friendships BEGIN SELECT RAISE(ABORT,'Friendships cannot be reassigned'); END;
--> statement-breakpoint
CREATE TRIGGER friendship_added AFTER INSERT ON friendships BEGIN
 DELETE FROM friend_likes WHERE (sender=NEW.a AND recipient=NEW.b) OR (sender=NEW.b AND recipient=NEW.a);
 UPDATE clique_settings SET revision=revision+1 WHERE owner IN(SELECT NEW.a UNION SELECT NEW.b); DELETE FROM group_likes WHERE sender IN(SELECT NEW.a UNION SELECT NEW.b) OR recipient IN(SELECT NEW.a UNION SELECT NEW.b); DELETE FROM group_matches WHERE a IN(SELECT NEW.a UNION SELECT NEW.b) OR b IN(SELECT NEW.a UNION SELECT NEW.b);
END;
--> statement-breakpoint
CREATE TRIGGER friendship_removed AFTER DELETE ON friendships BEGIN UPDATE clique_settings SET revision=revision+1 WHERE owner IN(SELECT OLD.a UNION SELECT OLD.b); DELETE FROM group_likes WHERE sender IN(SELECT OLD.a UNION SELECT OLD.b) OR recipient IN(SELECT OLD.a UNION SELECT OLD.b); DELETE FROM group_matches WHERE a IN(SELECT OLD.a UNION SELECT OLD.b) OR b IN(SELECT OLD.a UNION SELECT OLD.b); END;
--> statement-breakpoint
CREATE TRIGGER clique_consent_changed AFTER UPDATE OF enabled,groups_enabled ON clique_settings WHEN NEW.enabled<>OLD.enabled OR NEW.groups_enabled<>OLD.groups_enabled BEGIN UPDATE clique_settings SET revision=revision+1 WHERE owner IN(SELECT NEW.owner AS id UNION SELECT CASE WHEN fm.a=NEW.owner THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.owner OR fm.b=NEW.owner); DELETE FROM group_likes WHERE sender IN(SELECT NEW.owner AS id UNION SELECT CASE WHEN fm.a=NEW.owner THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.owner OR fm.b=NEW.owner) OR recipient IN(SELECT NEW.owner AS id UNION SELECT CASE WHEN fm.a=NEW.owner THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.owner OR fm.b=NEW.owner); DELETE FROM group_matches WHERE a IN(SELECT NEW.owner AS id UNION SELECT CASE WHEN fm.a=NEW.owner THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.owner OR fm.b=NEW.owner) OR b IN(SELECT NEW.owner AS id UNION SELECT CASE WHEN fm.a=NEW.owner THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.owner OR fm.b=NEW.owner); END;
--> statement-breakpoint
CREATE TRIGGER clique_profile_paused AFTER UPDATE OF paused ON profiles WHEN NEW.paused<>OLD.paused BEGIN UPDATE clique_settings SET revision=revision+1 WHERE owner IN(SELECT NEW.id AS id UNION SELECT CASE WHEN fm.a=NEW.id THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.id OR fm.b=NEW.id); DELETE FROM group_likes WHERE sender IN(SELECT NEW.id AS id UNION SELECT CASE WHEN fm.a=NEW.id THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.id OR fm.b=NEW.id) OR recipient IN(SELECT NEW.id AS id UNION SELECT CASE WHEN fm.a=NEW.id THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.id OR fm.b=NEW.id); DELETE FROM group_matches WHERE a IN(SELECT NEW.id AS id UNION SELECT CASE WHEN fm.a=NEW.id THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.id OR fm.b=NEW.id) OR b IN(SELECT NEW.id AS id UNION SELECT CASE WHEN fm.a=NEW.id THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.id OR fm.b=NEW.id); END;
--> statement-breakpoint
CREATE TRIGGER clique_blocked AFTER INSERT ON blocks BEGIN
 DELETE FROM friend_likes WHERE (sender=NEW.sender AND recipient=NEW.recipient) OR (sender=NEW.recipient AND recipient=NEW.sender);
 UPDATE clique_settings SET revision=revision+1 WHERE owner IN(SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender UNION SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient); DELETE FROM group_likes WHERE sender IN(SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender UNION SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient) OR recipient IN(SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender UNION SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient); DELETE FROM group_matches WHERE a IN(SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender UNION SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient) OR b IN(SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender UNION SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient);
 DELETE FROM friendships WHERE (a=NEW.sender AND b=NEW.recipient) OR (b=NEW.sender AND a=NEW.recipient);
END;
--> statement-breakpoint
CREATE TRIGGER group_like_guard BEFORE INSERT ON group_likes BEGIN
 SELECT CASE WHEN NOT (NEW.sender<>NEW.recipient
 AND EXISTS(SELECT 1 FROM profiles p JOIN profiles q ON p.scope=q.scope JOIN clique_settings cs ON cs.owner=p.id JOIN clique_settings ct ON ct.owner=q.id WHERE p.id=NEW.sender AND q.id=NEW.recipient AND cs.enabled=1 AND ct.enabled=1 AND p.paused=0 AND q.paused=0)
 AND NOT EXISTS(SELECT 1 FROM blocks k WHERE (k.sender=NEW.sender AND k.recipient=NEW.recipient) OR (k.sender=NEW.recipient AND k.recipient=NEW.sender)) AND (SELECT count(*) FROM friendships fc WHERE fc.a=NEW.sender OR fc.b=NEW.sender) BETWEEN 1 AND 4 AND (SELECT count(*) FROM friendships fc WHERE fc.a=NEW.sender OR fc.b=NEW.sender)=(SELECT count(*) FROM friendships fc WHERE fc.a=NEW.recipient OR fc.b=NEW.recipient)
 AND NOT EXISTS(SELECT 1 FROM (SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender) ma JOIN (SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient) mb ON ma.id=mb.id)
 AND NOT EXISTS(SELECT 1 FROM (SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender UNION SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient) mm JOIN profiles p ON p.id=mm.id LEFT JOIN clique_settings cs ON cs.owner=p.id WHERE p.paused=1 OR COALESCE(cs.enabled,0)=0 OR COALESCE(cs.groups_enabled,0)=0)
 AND NOT EXISTS(SELECT 1 FROM blocks k WHERE (k.sender IN(SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender) AND k.recipient IN(SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient)) OR (k.recipient IN(SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender) AND k.sender IN(SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient)))) THEN RAISE(ABORT,'Cliques must be separate, available, and the same size') END;
 SELECT CASE WHEN NEW.sender_revision<>(SELECT revision FROM clique_settings WHERE owner=NEW.sender) OR NEW.recipient_revision<>(SELECT revision FROM clique_settings WHERE owner=NEW.recipient) THEN RAISE(ABORT,'Clique membership changed') END;
END;
--> statement-breakpoint
CREATE TRIGGER group_match_guard BEFORE INSERT ON group_matches BEGIN
 SELECT CASE WHEN NEW.a>=NEW.b OR NEW.size<>(SELECT count(*) FROM friendships fc WHERE fc.a=NEW.a OR fc.b=NEW.a)+1 OR NOT (NEW.a<>NEW.b
 AND EXISTS(SELECT 1 FROM profiles p JOIN profiles q ON p.scope=q.scope JOIN clique_settings cs ON cs.owner=p.id JOIN clique_settings ct ON ct.owner=q.id WHERE p.id=NEW.a AND q.id=NEW.b AND cs.enabled=1 AND ct.enabled=1 AND p.paused=0 AND q.paused=0)
 AND NOT EXISTS(SELECT 1 FROM blocks k WHERE (k.sender=NEW.a AND k.recipient=NEW.b) OR (k.sender=NEW.b AND k.recipient=NEW.a)) AND (SELECT count(*) FROM friendships fc WHERE fc.a=NEW.a OR fc.b=NEW.a) BETWEEN 1 AND 4 AND (SELECT count(*) FROM friendships fc WHERE fc.a=NEW.a OR fc.b=NEW.a)=(SELECT count(*) FROM friendships fc WHERE fc.a=NEW.b OR fc.b=NEW.b)
 AND NOT EXISTS(SELECT 1 FROM (SELECT NEW.a AS id UNION SELECT CASE WHEN fm.a=NEW.a THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.a OR fm.b=NEW.a) ma JOIN (SELECT NEW.b AS id UNION SELECT CASE WHEN fm.a=NEW.b THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.b OR fm.b=NEW.b) mb ON ma.id=mb.id)
 AND NOT EXISTS(SELECT 1 FROM (SELECT NEW.a AS id UNION SELECT CASE WHEN fm.a=NEW.a THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.a OR fm.b=NEW.a UNION SELECT NEW.b AS id UNION SELECT CASE WHEN fm.a=NEW.b THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.b OR fm.b=NEW.b) mm JOIN profiles p ON p.id=mm.id LEFT JOIN clique_settings cs ON cs.owner=p.id WHERE p.paused=1 OR COALESCE(cs.enabled,0)=0 OR COALESCE(cs.groups_enabled,0)=0)
 AND NOT EXISTS(SELECT 1 FROM blocks k WHERE (k.sender IN(SELECT NEW.a AS id UNION SELECT CASE WHEN fm.a=NEW.a THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.a OR fm.b=NEW.a) AND k.recipient IN(SELECT NEW.b AS id UNION SELECT CASE WHEN fm.a=NEW.b THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.b OR fm.b=NEW.b)) OR (k.recipient IN(SELECT NEW.a AS id UNION SELECT CASE WHEN fm.a=NEW.a THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.a OR fm.b=NEW.a) AND k.sender IN(SELECT NEW.b AS id UNION SELECT CASE WHEN fm.a=NEW.b THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.b OR fm.b=NEW.b)))) THEN RAISE(ABORT,'Cliques must be separate, available, and the same size') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM group_likes WHERE sender=NEW.a AND recipient=NEW.b AND sender_revision=(SELECT revision FROM clique_settings WHERE owner=NEW.a) AND recipient_revision=(SELECT revision FROM clique_settings WHERE owner=NEW.b)) OR NOT EXISTS(SELECT 1 FROM group_likes WHERE sender=NEW.b AND recipient=NEW.a AND sender_revision=(SELECT revision FROM clique_settings WHERE owner=NEW.b) AND recipient_revision=(SELECT revision FROM clique_settings WHERE owner=NEW.a)) THEN RAISE(ABORT,'Both clique organizers must agree') END;
END;
--> statement-breakpoint
CREATE TRIGGER group_match_added AFTER INSERT ON group_matches BEGIN DELETE FROM group_likes WHERE (sender=NEW.a AND recipient=NEW.b) OR (sender=NEW.b AND recipient=NEW.a); END;
--> statement-breakpoint
CREATE TRIGGER group_match_immutable BEFORE UPDATE ON group_matches BEGIN SELECT RAISE(ABORT,'Group matches cannot be reassigned'); END;
--> statement-breakpoint
CREATE TRIGGER clique_message_guard BEFORE INSERT ON clique_messages BEGIN
 SELECT CASE WHEN (NEW.friendship IS NULL)=(NEW.group_match IS NULL) THEN RAISE(ABORT,'Choose one conversation') END;
 SELECT CASE WHEN NEW.friendship IS NOT NULL AND NOT EXISTS(SELECT 1 FROM friendships WHERE id=NEW.friendship AND (a=NEW.sender OR b=NEW.sender)) THEN RAISE(ABORT,'An active friendship is required') END;
 SELECT CASE WHEN NEW.group_match IS NOT NULL AND NOT EXISTS(SELECT 1 FROM group_matches g WHERE g.id=NEW.group_match AND (NEW.sender IN(SELECT g.a AS id UNION SELECT CASE WHEN fm.a=g.a THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=g.a OR fm.b=g.a) OR NEW.sender IN(SELECT g.b AS id UNION SELECT CASE WHEN fm.a=g.b THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=g.b OR fm.b=g.b))) THEN RAISE(ABORT,'An active clique match is required') END;
END;
