DROP TRIGGER group_like_guard;
--> statement-breakpoint
CREATE TRIGGER group_like_guard BEFORE INSERT ON group_likes BEGIN
 SELECT CASE WHEN NOT (NEW.sender<>NEW.recipient
 AND EXISTS(SELECT 1 FROM profiles p JOIN profiles q ON p.scope=q.scope JOIN clique_settings cs ON cs.owner=p.id JOIN clique_settings ct ON ct.owner=q.id WHERE p.id=NEW.sender AND q.id=NEW.recipient AND cs.enabled=1 AND ct.enabled=1 AND p.paused=0 AND q.paused=0)
 AND NOT EXISTS(SELECT 1 FROM blocks k WHERE (k.sender=NEW.sender AND k.recipient=NEW.recipient) OR (k.sender=NEW.recipient AND k.recipient=NEW.sender)) AND (SELECT count(*) FROM friendships fc WHERE fc.a=NEW.sender OR fc.b=NEW.sender) BETWEEN 1 AND 4 AND (SELECT count(*) FROM friendships fc WHERE fc.a=NEW.sender OR fc.b=NEW.sender)=(SELECT count(*) FROM friendships fc WHERE fc.a=NEW.recipient OR fc.b=NEW.recipient)
 AND NOT EXISTS(SELECT 1 FROM (SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender) ma JOIN (SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient) mb ON ma.id=mb.id)
 AND NOT EXISTS(SELECT 1 FROM (SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender UNION SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient) mm JOIN profiles p ON p.id=mm.id LEFT JOIN clique_settings cs ON cs.owner=p.id WHERE p.paused=1 OR COALESCE(cs.enabled,0)=0 OR COALESCE(cs.groups_enabled,0)=0)
 AND NOT EXISTS(SELECT 1 FROM blocks k WHERE k.sender IN(SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender UNION SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient) AND k.recipient IN(SELECT NEW.sender AS id UNION SELECT CASE WHEN fm.a=NEW.sender THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.sender OR fm.b=NEW.sender UNION SELECT NEW.recipient AS id UNION SELECT CASE WHEN fm.a=NEW.recipient THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.recipient OR fm.b=NEW.recipient))) THEN RAISE(ABORT,'Cliques must be separate, available, and the same size') END;
 SELECT CASE WHEN NEW.sender_revision<>(SELECT revision FROM clique_settings WHERE owner=NEW.sender) OR NEW.recipient_revision<>(SELECT revision FROM clique_settings WHERE owner=NEW.recipient) THEN RAISE(ABORT,'Clique membership changed') END;
END;
--> statement-breakpoint
DROP TRIGGER group_match_guard;
--> statement-breakpoint
CREATE TRIGGER group_match_guard BEFORE INSERT ON group_matches BEGIN
 SELECT CASE WHEN NEW.a>=NEW.b OR NEW.size<>(SELECT count(*) FROM friendships fc WHERE fc.a=NEW.a OR fc.b=NEW.a)+1 OR NOT (NEW.a<>NEW.b
 AND EXISTS(SELECT 1 FROM profiles p JOIN profiles q ON p.scope=q.scope JOIN clique_settings cs ON cs.owner=p.id JOIN clique_settings ct ON ct.owner=q.id WHERE p.id=NEW.a AND q.id=NEW.b AND cs.enabled=1 AND ct.enabled=1 AND p.paused=0 AND q.paused=0)
 AND NOT EXISTS(SELECT 1 FROM blocks k WHERE (k.sender=NEW.a AND k.recipient=NEW.b) OR (k.sender=NEW.b AND k.recipient=NEW.a)) AND (SELECT count(*) FROM friendships fc WHERE fc.a=NEW.a OR fc.b=NEW.a) BETWEEN 1 AND 4 AND (SELECT count(*) FROM friendships fc WHERE fc.a=NEW.a OR fc.b=NEW.a)=(SELECT count(*) FROM friendships fc WHERE fc.a=NEW.b OR fc.b=NEW.b)
 AND NOT EXISTS(SELECT 1 FROM (SELECT NEW.a AS id UNION SELECT CASE WHEN fm.a=NEW.a THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.a OR fm.b=NEW.a) ma JOIN (SELECT NEW.b AS id UNION SELECT CASE WHEN fm.a=NEW.b THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.b OR fm.b=NEW.b) mb ON ma.id=mb.id)
 AND NOT EXISTS(SELECT 1 FROM (SELECT NEW.a AS id UNION SELECT CASE WHEN fm.a=NEW.a THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.a OR fm.b=NEW.a UNION SELECT NEW.b AS id UNION SELECT CASE WHEN fm.a=NEW.b THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.b OR fm.b=NEW.b) mm JOIN profiles p ON p.id=mm.id LEFT JOIN clique_settings cs ON cs.owner=p.id WHERE p.paused=1 OR COALESCE(cs.enabled,0)=0 OR COALESCE(cs.groups_enabled,0)=0)
 AND NOT EXISTS(SELECT 1 FROM blocks k WHERE k.sender IN(SELECT NEW.a AS id UNION SELECT CASE WHEN fm.a=NEW.a THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.a OR fm.b=NEW.a UNION SELECT NEW.b AS id UNION SELECT CASE WHEN fm.a=NEW.b THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.b OR fm.b=NEW.b) AND k.recipient IN(SELECT NEW.a AS id UNION SELECT CASE WHEN fm.a=NEW.a THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.a OR fm.b=NEW.a UNION SELECT NEW.b AS id UNION SELECT CASE WHEN fm.a=NEW.b THEN fm.b ELSE fm.a END FROM friendships fm WHERE fm.a=NEW.b OR fm.b=NEW.b))) THEN RAISE(ABORT,'Cliques must be separate, available, and the same size') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM group_likes WHERE sender=NEW.a AND recipient=NEW.b AND sender_revision=(SELECT revision FROM clique_settings WHERE owner=NEW.a) AND recipient_revision=(SELECT revision FROM clique_settings WHERE owner=NEW.b)) OR NOT EXISTS(SELECT 1 FROM group_likes WHERE sender=NEW.b AND recipient=NEW.a AND sender_revision=(SELECT revision FROM clique_settings WHERE owner=NEW.b) AND recipient_revision=(SELECT revision FROM clique_settings WHERE owner=NEW.a)) THEN RAISE(ABORT,'Both clique organizers must agree') END;
END;
