import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {connectFriendsSql,replacementSql,friendCountSql,groupReadySql} from '../lib/clique-sql.ts';
function setup(){const d=new DatabaseSync(':memory:');d.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())d.exec(readFileSync('drizzle/'+f,'utf8'));d.exec("INSERT INTO spaces VALUES('s')");for(const id of 'abcdefghijklmnopqrst'.split('')){d.prepare("INSERT INTO profiles(id,scope,name,dob,gender,city,created) VALUES(?,'s',?,'1995-01-01','Nonbinary','NY',0)").run(id,id);d.prepare('INSERT INTO clique_settings(owner,enabled,groups_enabled) VALUES(?,1,1)').run(id);}return d;}
function like(d,a,b,replace=null){d.prepare('INSERT INTO friend_likes(sender,recipient,replacement,created) VALUES(?,?,?,0) ON CONFLICT(sender,recipient) DO UPDATE SET replacement=excluded.replacement').run(a,b,replace);}
function accept(d,a,b,replace=null){d.exec('BEGIN');try{like(d,a,b,replace);d.prepare(replacementSql()).run(a,b);d.prepare(replacementSql()).run(b,a);d.prepare(connectFriendsSql).run(a,b,crypto.randomUUID(),Date.now());d.exec('COMMIT');}catch(e){d.exec('ROLLBACK');throw e;}}
function pair(d,a,b){like(d,b,a);accept(d,a,b);}
function count(d,id){return d.prepare(`SELECT ${friendCountSql('?1')} n`).get(id).n;}
function has(d,a,b){return !!d.prepare('SELECT id FROM friendships WHERE (a=? AND b=?) OR (a=? AND b=?)').get(a,b,b,a);}
function glike(d,a,b){d.prepare('INSERT INTO group_likes(sender,recipient,sender_revision,recipient_revision) VALUES(?,?,(SELECT revision FROM clique_settings WHERE owner=?),(SELECT revision FROM clique_settings WHERE owner=?))').run(a,b,a,b);}
function gmatch(d,a,b,size=2){glike(d,a,b);glike(d,b,a);d.prepare('INSERT INTO group_matches(id,a,b,size,created) VALUES(?,?,?,?,0)').run(a+b,[a,b].sort()[0],[a,b].sort()[1],size);}
test('clique friendship requires mutual consent independently from dating slots',()=>{const d=setup();accept(d,'a','b');assert.equal(count(d,'a'),0);accept(d,'b','a');assert.equal(count(d,'a'),1);assert.equal(count(d,'b'),1);assert.equal(d.prepare('SELECT count(*) n FROM matches').get().n,0);});
test('a block within one clique prevents bringing both members into a new group chat',()=>{const d=setup();pair(d,'a','b');pair(d,'a','c');pair(d,'d','e');pair(d,'d','f');d.exec("INSERT INTO blocks(sender,recipient) VALUES('b','c')");assert.throws(()=>glike(d,'a','d'),/same size/);});
test('a full clique waits without removing friends until the new friendship is mutual',()=>{const d=setup();for(const b of ['b','c','d','e'])pair(d,'a',b);accept(d,'a','f','b');assert.equal(count(d,'a'),4);assert.ok(has(d,'a','b'));accept(d,'f','a');assert.equal(count(d,'a'),4);assert.ok(has(d,'a','f'));assert.ok(!has(d,'a','b'));assert.equal(count(d,'b'),0);});
test('both full participants must make their own replacement choices',()=>{const d=setup();for(const x of ['b','c','d','e'])pair(d,'a',x);for(const x of ['g','h','i','j'])pair(d,'f',x);accept(d,'a','f','b');accept(d,'f','a');assert.ok(has(d,'a','b'));assert.ok(has(d,'f','g'));assert.ok(!has(d,'a','f'));accept(d,'f','a','g');assert.ok(has(d,'a','f'));assert.equal(count(d,'a'),4);assert.equal(count(d,'f'),4);assert.equal(count(d,'b'),0);assert.equal(count(d,'g'),0);});
test('stale replacement does not remove any unchosen friend',()=>{const d=setup();for(const x of ['b','c','d','e'])pair(d,'a',x);accept(d,'a','f','b');like(d,'g','a');accept(d,'a','g','b');accept(d,'f','a');assert.ok(!has(d,'a','f'));assert.equal(count(d,'a'),4);assert.ok(has(d,'a','g'));});
test('insertion failure rolls back both replacement removals',()=>{const d=setup();for(const x of ['b','c','d','e'])pair(d,'a',x);like(d,'a','f','b');like(d,'f','a');d.exec('BEGIN');d.prepare(replacementSql()).run('a','f');assert.ok(!has(d,'a','b'));assert.throws(()=>d.prepare('INSERT INTO friendships VALUES(?,?,?,0)').run('bad','a','a'));d.exec('ROLLBACK');assert.ok(has(d,'a','b'));assert.equal(count(d,'a'),4);});
test('equal disjoint cliques match, and a roster change invalidates the connection',()=>{const d=setup();pair(d,'a','b');pair(d,'c','d');gmatch(d,'a','c');assert.equal(d.prepare('SELECT count(*) n FROM group_matches').get().n,1);pair(d,'a','e');assert.equal(d.prepare('SELECT count(*) n FROM group_matches').get().n,0);assert.equal(d.prepare('SELECT count(*) n FROM group_likes').get().n,0);});
test('different-sized, overlapping, solo, and non-consenting cliques cannot connect',()=>{const d=setup();pair(d,'a','b');pair(d,'c','d');pair(d,'c','e');assert.throws(()=>glike(d,'a','c'),/same size/);assert.throws(()=>glike(d,'a','b'),/same size/);assert.throws(()=>glike(d,'f','g'),/same size/);pair(d,'f','g');d.exec("UPDATE clique_settings SET groups_enabled=0 WHERE owner='g'");assert.throws(()=>glike(d,'a','f'),/same size/);});
test('cliques of five can connect; group chat admits exactly their current members',()=>{const d=setup();for(const x of ['b','c','d','e'])pair(d,'a',x);for(const x of ['g','h','i','j'])pair(d,'f',x);gmatch(d,'a','f',5);d.prepare("INSERT INTO clique_messages(id,group_match,sender,body,created) VALUES('m','af','b','Hi everyone',0)").run();assert.throws(()=>d.prepare("INSERT INTO clique_messages(id,group_match,sender,body,created) VALUES('n','af','k','No',0)").run(),/active clique/);d.exec("UPDATE clique_settings SET groups_enabled=0 WHERE owner='g'");assert.equal(d.prepare('SELECT count(*) n FROM group_matches').get().n,0);});
test('blocking removes mutual friendships and affected group connections',()=>{const d=setup();pair(d,'a','b');pair(d,'c','d');gmatch(d,'a','c');d.exec("INSERT INTO blocks(sender,recipient) VALUES('b','d')");assert.equal(d.prepare('SELECT count(*) n FROM group_matches').get().n,0);d.exec("INSERT INTO blocks(sender,recipient) VALUES('a','b')");assert.ok(!has(d,'a','b'));});
test('stale group invitations are rejected even after an equal-sized replacement',()=>{const d=setup();for(const x of ['b','c','d','e'])pair(d,'a',x);for(const x of ['g','h','i','j'])pair(d,'f',x);const old=d.prepare("SELECT revision FROM clique_settings WHERE owner='a'").get().revision;like(d,'k','a');accept(d,'a','k','b');assert.throws(()=>d.prepare('INSERT INTO group_likes(sender,recipient,sender_revision,recipient_revision) VALUES(?,?,?,(SELECT revision FROM clique_settings WHERE owner=?))').run('a','f',old,'f'),/membership changed/);});
