import {test} from "node:test";
import assert from "node:assert/strict";
import {DatabaseSync} from "node:sqlite";
import {readFileSync,readdirSync} from "node:fs";
import {promoteSql} from "../lib/matching-sql.ts";
function setup(names=["a","b","c","d","e","f","g","h"]){const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");for(const file of readdirSync("drizzle").filter(f=>f.endsWith(".sql")).sort())db.exec(readFileSync("drizzle/"+file,"utf8"));db.prepare("INSERT INTO spaces VALUES(?)").run("test");for(const id of names){db.prepare("INSERT INTO profiles(id,scope,name,dob,gender,city,created) VALUES(?,'test',?,'1995-01-01','Nonbinary','New York',0)").run(id,id);plan(db,id,"queue",true);}return db;}
function plan(db,id,addon,on){db.prepare("INSERT INTO plans(id,owner,addon,expires) VALUES(?,?,?,?) ON CONFLICT(owner,addon) DO UPDATE SET expires=excluded.expires").run(id+":"+addon,id,addon,on?Date.now()+86400000:0);}
function like(db,a,b){db.prepare("INSERT OR IGNORE INTO likes(sender,recipient) VALUES(?,?)").run(a,b);}
function pair(db,a,b){like(db,a,b);like(db,b,a);}
function promote(db,a,operation){const vals=[crypto.randomUUID(),a,Date.now(),a];if(operation)vals.push(operation);return db.prepare(promoteSql(!!operation)).run(...vals);}
function count(db,a){return db.prepare("SELECT count(*) n FROM matches WHERE ended IS NULL AND (a=? OR b=?)").get(a,a).n;}
test("free mutual match is atomic, consumes likes, and locks outgoing swipes",()=>{const d=setup();pair(d,"a","b");promote(d,"a");assert.equal(count(d,"a"),1);assert.equal(d.prepare("SELECT count(*) n FROM likes").get().n,0);assert.throws(()=>like(d,"a","c"),/capacity/);assert.throws(()=>d.prepare("INSERT INTO passes(sender,recipient) VALUES('a','c')").run(),/capacity/);like(d,"c","a");assert.equal(d.prepare("SELECT count(*) n FROM likes WHERE recipient='a'").get().n,1);});
test("one-sided likes never create a match; repeats retain the original position",()=>{const d=setup();like(d,"a","b");const n=d.prepare("SELECT id FROM likes").get().id;like(d,"a","b");promote(d,"b");assert.equal(count(d,"b"),0);assert.equal(d.prepare("SELECT id FROM likes").get().id,n);});
test("five slots are enforced for each endpoint; downgrade keeps existing matches",()=>{const d=setup();plan(d,"a","capacity",true);for(const b of ["b","c","d","e","f","g"])pair(d,"a",b);for(let i=0;i<8;i++)promote(d,"a");assert.equal(count(d,"a"),5);assert.equal(count(d,"g"),0);assert.throws(()=>like(d,"a","h"),/capacity/);plan(d,"a","capacity",false);assert.equal(count(d,"a"),5);assert.throws(()=>like(d,"a","h"),/capacity/);promote(d,"g");assert.equal(count(d,"g"),0);});
test("FIFO is enforced unless queue freedom is active",()=>{const d=setup();plan(d,"a","queue",false);like(d,"b","a");like(d,"c","a");assert.throws(()=>like(d,"a","c"),/oldest/);like(d,"a","b");assert.equal(d.prepare("SELECT count(*) n FROM likes WHERE sender='a'").get().n,1);like(d,"a","c");const e=setup();plan(e,"a","queue",false);like(e,"b","a");like(e,"c","a");plan(e,"a","queue",true);like(e,"a","c");promote(e,"a");assert.equal(e.prepare("SELECT b FROM matches WHERE a='a'").get().b,"c");});
test("busy head preserves place while next eligible mutual connection is promoted",()=>{const d=setup();pair(d,"b","c");like(d,"b","a");pair(d,"a","d");like(d,"a","b");promote(d,"b");promote(d,"a");assert.equal(d.prepare("SELECT b FROM matches WHERE a='a'").get().b,"d");assert.ok(d.prepare("SELECT id FROM likes WHERE sender='b' AND recipient='a'").get());});
test("unmatch operation cannot revive a match or change participants",()=>{const d=setup();pair(d,"a","b");promote(d,"a");d.prepare("UPDATE matches SET ended=1,operation='end'").run();promote(d,"a","end");promote(d,"b","end");assert.equal(count(d,"a"),0);assert.throws(()=>d.prepare("UPDATE matches SET ended=NULL").run(),/immutable/);assert.throws(()=>d.prepare("UPDATE matches SET b='c'").run(),/immutable/);});
test("active paid partners cannot create new likes to rematch each other",()=>{const d=setup();plan(d,"a","capacity",true);pair(d,"a","b");promote(d,"a");assert.throws(()=>like(d,"a","b"),/Already matched/);});
test("block atomically closes an active pair and blocks communication",()=>{const d=setup();pair(d,"a","b");promote(d,"a");const mid=d.prepare("SELECT id FROM matches").get().id;d.exec("BEGIN");d.prepare("INSERT INTO blocks(sender,recipient) VALUES('a','b')").run();d.prepare("DELETE FROM likes WHERE (sender='a' AND recipient='b') OR (sender='b' AND recipient='a')").run();d.prepare("UPDATE matches SET ended=1,operation='block' WHERE ended IS NULL AND ((a='a' AND b='b') OR (a='b' AND b='a'))").run();d.exec("COMMIT");assert.equal(count(d,"a"),0);assert.throws(()=>like(d,"b","a"),/unavailable/);assert.throws(()=>d.prepare("INSERT INTO messages(id,match_id,sender,body,created) VALUES('x',?,'b','hello',0)").run(mid),/active connection/);});
test("hidden passed profiles cannot obstruct FIFO",()=>{const d=setup();plan(d,"a","queue",false);like(d,"b","a");d.prepare("INSERT INTO passes(sender,recipient) VALUES('a','b')").run();d.prepare("DELETE FROM likes WHERE sender='b' AND recipient='a'").run();like(d,"b","a");like(d,"c","a");like(d,"a","c");promote(d,"a");assert.equal(count(d,"c"),1);});
test("failed transaction rolls back request IDs and mutations",()=>{const d=setup();pair(d,"a","b");promote(d,"a");d.exec("BEGIN");try{d.prepare("INSERT INTO requests(id,payload,created) VALUES('retry','{}',0)").run();like(d,"a","c");d.exec("COMMIT");}catch{d.exec("ROLLBACK");}assert.equal(d.prepare("SELECT count(*) n FROM requests").get().n,0);});
test("clock and reciprocal interest can coexist while a person is matched",()=>{const d=setup();like(d,"b","a");pair(d,"b","c");promote(d,"b");assert.equal(count(d,"b"),1);assert.ok(d.prepare("SELECT id FROM likes WHERE sender='b' AND recipient='a'").get());like(d,"a","b");promote(d,"a");assert.equal(count(d,"a"),0);d.prepare("UPDATE matches SET ended=1,operation='free-b' WHERE ended IS NULL AND (a='b' OR b='b')").run();promote(d,"b","free-b");assert.equal(count(d,"a"),1);});

