"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {UsersRound,UserPlus,Check,X,MessageCircle,ArrowRight,Send,MapPin} from "lucide-react";
import {toast} from "sonner";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Avatar,Vacant} from "./panels";
import {clearSubmittedDraft} from "@/lib/view-state";
import type {CliqueState,FriendProfile,CliqueGroup} from "@/lib/clique-types";

export function CliquePanel({mode}:{mode:"demo"|"live"}){
 const [state,setState]=useState<CliqueState|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('find'),[busy,setBusy]=useState(false),[gender,setGender]=useState('Everyone'),[interest,setInterest]=useState('');
 const [detail,setDetail]=useState<FriendProfile|null>(null),[replacement,setReplacement]=useState<FriendProfile|null>(null),[choice,setChoice]=useState(''),[reportText,setReportText]=useState(''),[confirm,setConfirm]=useState<{action:string;id:string;name:string}|null>(null),[room,setRoom]=useState(''),[drafts,setDrafts]=useState<Record<string,string>>({}),[skippedGroups,setSkippedGroups]=useState<string[]>([]);
 const live=useRef(true),pending=useRef(false),sequence=useRef(0),touch=useRef<number|null>(null);
 const refresh=useCallback(async()=>{const seq=++sequence.current;try{const r=await fetch('/api/clique?mode='+mode,{cache:'no-store'}),s=await r.json() as CliqueState & {error?:string};if(!r.ok)throw Error(s.error);if(live.current&&sequence.current===seq){setState(s);setError('');}}catch(e:any){if(live.current&&sequence.current===seq)setError(e.message);}},[mode]);
 useEffect(()=>{live.current=true;void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!pending.current)void refresh();},8000);return()=>{live.current=false;sequence.current++;clearInterval(timer);};},[refresh]);
 async function act(action:string,extra:Record<string,unknown>={}){if(pending.current)return null;pending.current=true;sequence.current++;setBusy(true);try{const r=await fetch('/api/clique',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,action,requestId:crypto.randomUUID(),...extra})}),s=await r.json() as CliqueState & {error?:string};if(!r.ok)throw Error(s.error);if(!live.current)return null;sequence.current++;setState(s);setError('');return s as CliqueState;}catch(e:any){if(live.current){toast.error(e.message);void refresh();}return null;}finally{pending.current=false;if(live.current)setBusy(false);}}
 const candidates=state?.profiles.filter(p=>(gender==='Everyone'||p.gender===gender)&&(!interest||p.interests.some(t=>t.toLowerCase().includes(interest.toLowerCase()))))||[],person=candidates[0];
 async function like(p:FriendProfile,replace?:string){if(!state)return;if(state.friends.length>=4&&!replace){setReplacement(p);setChoice('');return;}const next=await act('like',{target:p.id,replacement:replace||null});if(next){setReplacement(null);setDetail(null);toast.success(next.friends.some(f=>f.id===p.id)?p.name+' joined your clique.':'Friend request sent. Your current clique stays together until the new friendship is mutual.');}}
 async function pass(p:FriendProfile){if(await act('pass',{target:p.id}))setDetail(null);}
 const groups=state?.groups.filter(g=>!skippedGroups.includes(g.owner.id))||[],group=groups[0];
 const rooms=[...(state?.friends||[]).map(p=>({id:p.friendshipId!,title:p.name,friendshipId:p.friendshipId,groupMatchId:undefined})),...(state?.groupMatches||[]).map(g=>({id:g.matchId!,title:g.owner.name+"'s clique",friendshipId:undefined,groupMatchId:g.matchId}))];
 const activeRoom=rooms.find(r=>r.id===room)||rooms[0],draft=activeRoom?drafts[activeRoom.id]||'':'';
 const send=async()=>{if(!activeRoom||!draft.trim())return;const id=activeRoom.id,submitted=draft;const next=await act('message',{friendshipId:activeRoom.friendshipId,groupMatchId:activeRoom.groupMatchId,text:submitted});if(next)setDrafts(current=>clearSubmittedDraft(current,id,submitted));};
 function roster(g:CliqueGroup){return <div className="clique-roster">{g.members.map(p=><button key={p.id} onClick={()=>setDetail(p)}><Avatar person={p}/><span>{p.name}</span></button>)}</div>;}
 if(!state)return <div className="panel-card" role="status">{error||'Finding your people…'}{error&&<button className="secondary" onClick={()=>refresh()}>Try again</button>}</div>;
 return <section className="clique-surface"><div className="page-heading"><div><div className="eyebrow">DBD · FRIENDSHIP, ON PURPOSE</div><h1>Find your <em>clique.</em></h1><p>All genders welcome. Four friends. More things to do together.</p></div><span className="clique-capacity"><UsersRound size={19}/>{state.friends.length}/4 friends</span></div>
 {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>refresh()}>Try again</button></div>}
 {!state.enabled&&!state.friends.length&&!state.outgoing.length?<Vacant title="A new chapter, with friends." description="Clique is for platonic connections across all genders. Your friendships and dating matches stay separate. Join to make your profile visible to other people looking for friends."><button className="primary" disabled={busy} onClick={()=>act('settings',{enabled:true,groupsEnabled:false})}><UserPlus size={18}/> Start my clique</button></Vacant>:<>
 <div className="clique-tabs" role="tablist" aria-label="Clique views">{[['find','Find friends'],['mine','My clique'],['groups','Meet a clique'],['chat','Conversations']].map(([id,label])=><button role="tab" aria-selected={tab===id} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='find'&&<><div className="clique-filters"><label>Friendship preference<select aria-label="Friendship gender preference" value={gender} onChange={e=>setGender(e.target.value)}>{['Everyone','Woman','Man','Nonbinary'].map(g=><option key={g}>{g}</option>)}</select></label><label>Shared interest<input aria-label="Friendship interest" placeholder="Coffee, art, hiking…" value={interest} onChange={e=>setInterest(e.target.value)}/></label></div><div className="discover-layout"><div>{person?<><div className="clique-discovery-card" onTouchStart={e=>touch.current=e.changedTouches[0].clientX} onTouchEnd={e=>{if(touch.current!==null&&!busy){const delta=e.changedTouches[0].clientX-touch.current;if(delta>85)void like(person);else if(delta< -85)void pass(person);}touch.current=null;}}>{person.photos[0]?<img src={person.photos[0]} alt={person.name}/>:<div className="clique-initial">{person.name[0]}</div>}<div className="clique-card-copy"><span className="tag"><UsersRound size={14}/> Platonic friendship</span>{person.likesYou&&<span className="friend-check"><Check size={16}/> Wants to be friends</span>}<h2><button onClick={()=>setDetail(person)}>{person.name}, {person.age}</button></h2><p><MapPin size={14}/>{person.city} · {person.friendCount}/4 friends</p></div></div><div className="swipe-actions"><button className="round-action pass" disabled={busy} aria-label={'Pass on friend '+person.name} onClick={()=>pass(person)}><X/></button><span>A little more together.</span><button className="round-action like" disabled={busy} aria-label={'Befriend '+person.name} onClick={()=>like(person)}><UserPlus/></button></div><div className="about-card"><p>{person.bio}</p><div className="interests">{person.interests.map(t=><span className="tag" key={t}>{t}</span>)}</div><button className="text-button" onClick={()=>setDetail(person)}>See full profile</button></div></>:<Vacant title="You've met this little corner." description="Adjust your friendship preferences or check back as more people join."/>}</div><aside className="context-column"><div className="panel-card"><UsersRound/><h3>A small circle. A bigger world.</h3><p>You and up to four mutual friends make your clique. Everyone chooses their own friends.</p><p>At four friends, choose someone to replace when making a new connection. Both sides of the old friendship are removed only when the new one becomes mutual.</p><p>Friends can have different personal cliques. A clique meetup includes an organizer and all of their current friends.</p></div><div className="panel-card"><h3>Friendship comes first.</h3><p>Keep invitations platonic, respect boundaries, and report unwanted romantic or sexual advances using Report and block on their profile.</p><p>Unlimited swipes. No dating match slots used.</p></div></aside></div></>}
 {tab==='mine'&&<><div className="panel-card"><h3>You + {state.friends.length} friends.</h3><p>{state.friends.length===4?'Your clique is full. You can still meet people and choose a replacement.':'Room for '+(4-state.friends.length)+' more mutual friends.'}</p>{state.friends.map(p=><div className="queue-row" key={p.id}><Avatar person={p}/><button className="row-person" onClick={()=>setDetail(p)}><strong>{p.name}</strong><span>{p.city}</span></button><button className="secondary" onClick={()=>{setRoom(p.friendshipId!);setTab('chat');}}><MessageCircle size={16}/> Chat</button><button className="text-button" onClick={()=>setConfirm({action:'remove',id:p.friendshipId!,name:p.name})}>Remove</button></div>)}{!state.friends.length&&<button className="primary" onClick={()=>setTab('find')}>Find your first friend</button>}</div><div className="panel-card"><h3>Friend requests</h3><p>Requests wait until both people choose each other and can make room.</p>{[...state.incoming,...state.outgoing.filter(p=>!state.incoming.some(q=>q.id===p.id))].map(p=><div className="queue-row" key={p.id}><Avatar person={p}/><button className="row-person" onClick={()=>setDetail(p)}><strong>{p.name}</strong><span>{p.likesYou?(p.liked?'Mutual interest · waiting for room':'Wants to be friends'):'Your request is waiting'}{p.replacement?' · Replacement selected':''}</span></button><button className="secondary" disabled={busy} onClick={()=>like(p)}>{state.friends.length>=4?'Choose replacement':p.liked?'Check availability':'Accept'}</button>{p.liked&&<button className="text-button" disabled={busy} onClick={()=>act('withdraw',{target:p.id})}>Withdraw</button>}</div>)}</div><button className="text-button" disabled={busy} onClick={()=>act('settings',{enabled:!state.enabled,groupsEnabled:false})}>{state.enabled?'Pause Clique discovery':'Resume Clique discovery'}</button><p className="fine-print">Pausing keeps your friendships and closes clique meetups involving your profile.</p></>}
 {tab==='groups'&&<><div className="panel-card"><h3>Clique, meet clique.</h3><p>Your meetup group is you and all {state.friends.length} of your current friends: {state.friends.length+1} total people. You can match with a separate clique of the same size.</p><label className="clique-consent"><input type="checkbox" checked={state.groupsEnabled} disabled={busy} onChange={e=>act('settings',{enabled:true,groupsEnabled:e.target.checked})}/><span>Include me in clique discovery and group conversations. Other cliques can view my profile and the roster.</span></label><p className="fine-print">Every member must opt in. Roster changes clear previous group requests and matches. Group matching does not create individual friendships.</p></div>{!state.readyForGroups?<Vacant title={state.friends.length?'Get everyone on board.':'Start with one friend.'} description={state.friends.length?'You and each friend must enable clique discovery before your group can meet another clique.':'Build a clique of two to five total people to enter group discovery.'}/>:group?<div className="panel-card clique-group-card"><span className="tag">{group.members.length} + {group.members.length} people</span><h2>{group.owner.name}'s clique</h2><p>{group.owner.city}{group.likesYou?' · Their organizer liked your clique':''}</p>{roster(group)}<div className="button-row"><button className="secondary" disabled={busy} onClick={()=>setSkippedGroups(current=>[...current,group.owner.id])}>Next clique</button><button className="primary" disabled={busy||group.liked} onClick={async()=>{const next=await act('group-like',{target:group.owner.id,revision:state.revision,targetRevision:group.revision});if(next)toast.success(next.groupMatches.some(g=>g.owner.id===group.owner.id)?"Your cliques connected!":"Clique invitation sent.");}}>{group.liked?<Check size={17}/>:<UserPlus size={17}/>} {group.liked?'Invitation sent':'Connect cliques'}</button></div>{mode==='demo'&&group.liked&&<button className="demo-reply" disabled={busy} onClick={()=>act('demo-group-reply',{target:group.owner.id})}>Simulate their organizer accepting · demo only</button>}</div>:<Vacant title="Your next group adventure is on its way." description={'No other available cliques of '+(state.friends.length+1)+' people right now.'}>{skippedGroups.length>0&&<button className="secondary" onClick={()=>setSkippedGroups([])}>Review skipped cliques</button>}</Vacant>}{state.groupMatches.length>0&&<div className="panel-card"><h3>Your clique connections</h3>{state.groupMatches.map(g=><div key={g.matchId} className="clique-group-result"><h3>{g.owner.name}'s clique · {g.members.length} people</h3>{roster(g)}<div className="button-row"><button className="primary" onClick={()=>{setRoom(g.matchId!);setTab('chat');}}>Open group conversation <ArrowRight size={16}/></button><button className="text-button" onClick={()=>setConfirm({action:'group-end',id:g.matchId!,name:g.owner.name+"'s clique"})}>End group connection</button></div></div>)}</div>}</>}
 {tab==='chat'&&(activeRoom?<><div className="connection-tabs">{rooms.map(r=><button key={r.id} className={r.id===activeRoom.id?'selected':''} onClick={()=>setRoom(r.id)}>{r.title}</button>)}</div><div className="chat-panel"><header className="chat-header"><UsersRound/><strong>{activeRoom.title}</strong></header><div className="chat-messages" aria-live="polite">{state.messages.filter(m=>(m.friendship||m.group_match)===activeRoom.id).map(m=><div className={'bubble '+(m.sender===state.viewer?.id?'sent':'received')} key={m.id}><small>{m.name}</small><p>{m.body}</p><time>{new Date(m.created).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}</time></div>)}{!state.messages.some(m=>(m.friendship||m.group_match)===activeRoom.id)&&<div className="conversation-start"><h3>Good company starts with a hello.</h3><p>Suggest a coffee, a walk, or something you all enjoy.</p></div>}</div><form className="message-form" onSubmit={e=>{e.preventDefault();void send();}}><input aria-label="Clique message" placeholder="Make a little plan…" value={draft} maxLength={2000} onChange={e=>setDrafts(current=>({...current,[activeRoom.id]:e.target.value}))}/><button className="send-button" aria-label="Send clique message" disabled={busy||!draft.trim()}><Send size={19}/></button></form></div></>:<Vacant title="Make room for a hello." description="Your mutual friends and connected cliques have conversations here."/>)}
 </>}
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="dbd-dialog clique-detail"><DialogHeader><DialogTitle>{detail?.name}, {detail?.age}</DialogTitle><DialogDescription>{detail?.city} · Platonic friendship</DialogDescription></DialogHeader>{detail&&<>{detail.photos[0]&&<img className="sheet-photo" src={detail.photos[0]} alt={detail.name}/>}<p>{detail.bio}</p><div className="interests">{detail.interests.map(t=><span className="tag" key={t}>{t}</span>)}</div><blockquote>{detail.prompt}</blockquote>{detail.id!==state.viewer?.id&&<button className="danger-text" onClick={()=>{setReportText("");setConfirm({action:"report",id:detail.id,name:detail.name});setDetail(null);}}>Report and block</button>}</>}</DialogContent></Dialog>
 <Dialog open={!!replacement} onOpenChange={v=>{if(!v)setReplacement(null);}}><DialogContent className="dbd-dialog"><DialogHeader><DialogTitle>Make room for {replacement?.name}?</DialogTitle><DialogDescription>You have four friends. Choose the friendship to end if this new connection becomes mutual. You and the replaced friend will leave each other's cliques; affected clique meetups also close.</DialogDescription></DialogHeader><div className="form-stack">{state.friends.map(p=><label className="clique-consent" key={p.id}><input type="radio" name="replacement" value={p.id} checked={choice===p.id} onChange={()=>setChoice(p.id)}/><Avatar person={p}/>{p.name}</label>)}<p className="fine-print">No one is removed while your request is waiting.</p><button className="primary" disabled={busy||!choice} onClick={()=>replacement&&like(replacement,choice)}>Confirm replacement choice</button></div></DialogContent></Dialog>
 <Dialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(null);}}><DialogContent className="dbd-dialog"><DialogHeader><DialogTitle>{confirm?.action==="report"?"Report and block":"Disconnect from"} {confirm?.name}?</DialogTitle><DialogDescription>{confirm?.action==='report'?"This stores your report and blocks this person in dating and Clique. Existing connections end. Reports are not monitored in real time.":confirm?.action==='remove'?"This removes both sides of the friendship and closes affected clique meetups.":"This ends the meetup connection and its conversation for both cliques."}</DialogDescription></DialogHeader>{confirm?.action==="report"&&<textarea aria-label="Clique report details" placeholder="Tell us what happened" maxLength={1200} value={reportText} onChange={e=>setReportText(e.target.value)}/>}<button className="primary" disabled={busy} onClick={async()=>{if(!confirm)return;const next=await act(confirm.action,confirm.action==='report'?{target:confirm.id,details:reportText}:confirm.action==='remove'?{friendshipId:confirm.id}:{groupMatchId:confirm.id});if(next)setConfirm(null);}}>{confirm?.action==="report"?"Report and block":"Disconnect"}</button></DialogContent></Dialog>
 </section>;
}
