"use client";
import {useState,useEffect,FormEvent} from "react";
import {Heart,Layers,Crown,Check,Clock3,Flag,X,Camera,LoaderCircle,RotateCcw} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Switch} from "@/components/ui/switch";
import {Slider} from "@/components/ui/slider";
import {toast} from "sonner";
import {Avatar} from "./panels";
import {defaults} from "./dating-app";
function Choice({value,onChange,options,label}:any){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map((v:string)=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
export function Modals({c}:{c:any}){
 const {mode,setMode,state,me,full,modalMatch:active,modal,setModal,detail,setDetail,confirm,setConfirm,filters,setFilters,act,swipe,working}=c;
 const [reason,setReason]=useState("Inappropriate behavior"),[report,setReport]=useState(""),[venue,setVenue]=useState(""),[when,setWhen]=useState(""),[edit,setEdit]=useState<any>(null),[consent,setConsent]=useState(false),[uploading,setUploading]=useState(false),[paying,setPaying]=useState(false);
 useEffect(()=>{if(modal==="date"){setVenue("");setWhen("");}},[modal,active?.id]);
 useEffect(()=>{if(modal==="edit")setEdit(me?{name:me.name,dob:"",gender:me.gender,city:me.city,job:me.job,bio:me.bio,intent:me.intent,interests:me.interests.join(", "),photos:me.photos,prompt:me.prompt,paused:me.paused}:{name:"",dob:"",gender:"Woman",city:"",job:"",bio:"",intent:"Long-term relationship",interests:"",photos:[],prompt:"",paused:false});},[modal]);
 async function save(e:FormEvent){e.preventDefault();const next=await act("profile",{profile:{...edit,dob:edit.dob||undefined,interests:edit.interests.split(",").map((s:string)=>s.trim()).filter(Boolean)},consent});if(next){setModal("");toast.success("Your profile is saved.");}}
 async function upload(file?:File){if(!file)return;setUploading(true);try{if(file.size>5*1024*1024)throw new Error("Use a photo under 5 MB.");const bitmap=await createImageBitmap(file);const canvas=document.createElement("canvas");const scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d")!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const clean=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("Unable to read this image.")),"image/jpeg",.9));const f=new FormData();f.append("file",clean,"profile.jpg");const r=await fetch("/api/photos?mode="+mode,{method:"POST",body:f});const data:any=await r.json();if(!r.ok)throw new Error(data.error);setEdit((p:any)=>({...p,photos:[...p.photos,data.url].slice(0,6)}));}catch(e:any){toast.error(e.message);}finally{setUploading(false);}}
 async function billing(action:string,addon?:string){setPaying(true);try{const r=await fetch("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,addon})});const s:any=await r.json();if(!r.ok)throw new Error(s.error);window.location.assign(s.url);}catch(e:any){toast.error(e.message);setPaying(false);}}
 const titles:any={preferences:"Your kind of connection",rules:"A queue with a little more clarity",safety:"Date with care",demo:"Make yourself at home",edit:me?"Edit your profile":"Create your profile",date:"Something to look forward to",plans:"Date at your own pace",report:"Report & block",transparency:active?.partner.name+"'s connections","connection-options":"Your connection"};
 return <><Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal("");}}><DialogContent className={"dbd-dialog "+(modal==="plans"?"plans-dialog":"")}><DialogHeader><DialogTitle>{titles[modal]||"Date-By-Date"}</DialogTitle><DialogDescription>{modal==="plans"?"Unlimited swipes for everyone. More choice, only if you want it.":modal==="edit"?"A little honesty goes a long way.":modal==="transparency"?"Current matches and incoming interest. Conversations stay private.":"One thoughtful choice at a time."}</DialogDescription></DialogHeader>
 {modal==="preferences"&&<div className="form-stack"><label>Age range <b>{filters.ages[0]}–{filters.ages[1]}</b></label><Slider min={18} max={80} step={1} value={filters.ages} onValueChange={v=>setFilters({...filters,ages:v})} aria-label="Age range"/><label>I'd like to meet</label><Choice label="Gender preference" value={filters.gender} onChange={(v:string)=>setFilters({...filters,gender:v})} options={["Everyone","Woman","Man","Nonbinary"]}/><label>City or neighborhood<input value={filters.city} placeholder="Anywhere" onChange={e=>setFilters({...filters,city:e.target.value})}/></label><div className="premium-filter-label"><Crown size={15}/> Advanced filters · DBD Plus</div>{state?.plans.capacity?<><Choice label="Relationship intention" value={filters.intent} onChange={(v:string)=>setFilters({...filters,intent:v})} options={["Any intention","Long-term relationship","Open to exploring","Life partner"]}/><label>Shared interest<input value={filters.interest} onChange={e=>setFilters({...filters,interest:e.target.value})} placeholder="Art, hiking, coffee..."/></label></>:<button className="secondary" onClick={()=>setModal("plans")}>Explore advanced filters</button>}<p className="fine-print">Incoming likes keep their arrival order, regardless of discovery filters.</p><div className="button-row"><button className="secondary" onClick={()=>setFilters(defaults)}>Reset</button><button className="primary" onClick={()=>{localStorage.setItem("dbd-filters",JSON.stringify(filters));void c.refresh();setModal("");}}>Save preferences</button></div></div>}
 {modal==="rules"&&<div className="prose-copy"><p><b>A right swipe is an invitation.</b> It joins the other person's queue in the order it arrives. Duplicate likes never move your spot.</p><p><b>A match needs two yeses and room on both sides.</b> When a slot opens, the oldest eligible mutual like becomes a match. People at capacity keep their place while waiting.</p><p><b>Your incoming likes come first, oldest first.</b> Like or pass to continue. Queue Freedom lets you choose any incoming profile without rearranging anyone's queue.</p><p><b>No daily swipe limits.</b> Free accounts have one match slot; DBD Plus has five. Browsing pauses when your slots are full.</p><p><b>The icons tell the story.</b> A clock means they're matched, a green check means they liked you, and both can appear together. Outstanding outgoing likes appear on the right.</p></div>}
 {modal==="safety"&&<div className="prose-copy"><p><b>18 and over.</b> DBD is for adults. Profiles are self-reported; photos and identities have not been independently verified.</p><p><b>Start somewhere public.</b> Tell someone you trust about your plans. Keep financial and sensitive personal details private.</p><p><b>You can leave any connection.</b> Unmatch at any time. Blocking removes mutual visibility and prevents future contact. Reports are stored; this first version does not provide a staffed, real-time moderation service.</p><p><b>Dating activity is visible.</b> A DBD Plus member matched with someone can see that person's other matches and incoming queue, including your profile if you're in either list. Chats, birthday, contact details, and billing information remain private.</p><p className="fine-print">Demo people are fictional. Photos are illustrative stock portraits and do not imply participation or endorsement. Photo credits: Josue Velasquez, IULIIA TIUNOVA, Anh Tuấn Lê, Sóc Năng Động, and nappy on Pexels.</p></div>}
 {modal==="demo"&&<div className="form-stack"><p className="prose-copy">The demo is your private sandbox. Profiles, likes, and replies are fictional. Your actions are saved separately from live dating.</p><div className="button-row"><button className={mode==="demo"?"primary":"secondary"} onClick={()=>{setMode("demo");setModal("");}}>Explore demo</button><button className={mode==="live"?"primary":"secondary"} onClick={()=>{setMode("live");setModal("");}}>Use my real profile</button></div>{mode==="demo"&&<><button className="secondary" onClick={()=>setModal("plans")}>Try paid features in the demo</button><button className="text-button" disabled={working} onClick={()=>setConfirm({action:"reset-demo",title:"Reset your demo?",description:"This clears only your fictional demo likes, matches, conversations, and upgrades."})}><RotateCcw size={16}/> Reset demo</button></>}</div>}
 {modal==="plans"&&<><div className="plan-grid">{[{id:"capacity",name:"DBD Plus",icon:Heart,features:["Up to 5 active matches","Your connections' other matches & queues","Advanced discovery filters","Unlimited undo for passes"]},{id:"queue",name:"Queue Freedom",icon:Layers,features:["Review incoming likes in any order","Choose the profiles that spark curiosity","Keep your place in everyone else's queue","Works with Free or DBD Plus"]}].map(plan=>{const enabled=state?.plans[plan.id];return <div className={"plan-card "+(enabled?"enabled":"")} key={plan.id}><plan.icon/><h3>{plan.name}</h3><div className="price">$4.99<span>/month</span></div>{plan.features.map(t=><p key={t}><Check size={15}/>{t}</p>)}{mode==="demo"?<button className={enabled?"secondary":"primary"} disabled={working||!me} onClick={()=>act("demo-plan",{addon:plan.id,enabled:!enabled})}>{enabled?"Turn off in demo":"Try in demo"}</button>:<button className={enabled?"secondary":"primary"} disabled={paying||!state?.billingEnabled} onClick={()=>billing(enabled?"portal":"checkout",plan.id)}>{enabled?"Manage subscription":state?.billingEnabled?"Subscribe":"Billing not connected yet"}</button>}</div>})}</div><p className="fine-print">Independent monthly add-ons. Both together: $9.98/month. Capacity tops out at five. Cancel renewal in billing; access lasts through the paid period. Existing matches stay if you downgrade. Unlimited swipes, messaging, safety tools, and date planning are free.</p>{mode==="demo"&&<div className="demo-callout">Demo upgrades are free to try. No payment is taken.</div>}</>}
 {modal==="edit"&&edit&&<form className="form-stack" onSubmit={save}><div className="photo-upload-grid">{edit.photos.map((url:string,i:number)=><div key={url}><img src={url} alt={"Profile photo "+(i+1)}/><button type="button" aria-label={"Remove photo "+(i+1)} onClick={()=>setEdit({...edit,photos:edit.photos.filter((_:string,n:number)=>n!==i)})}><X size={13}/></button></div>)}{edit.photos.length<6&&<label className="upload-tile">{uploading?<LoaderCircle className="animate-spin"/>:<Camera/>}<span>Add photo</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>upload(e.target.files?.[0])}/></label>}</div><div className="form-two"><label>First name<input required minLength={2} maxLength={40} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>{me?"Birth date (optional update)":"Birth date · 18+"}<input type="date" required={!me} value={edit.dob} onChange={e=>setEdit({...edit,dob:e.target.value})}/></label></div><label>Gender</label><Choice label="Gender" value={edit.gender} onChange={(v:string)=>setEdit({...edit,gender:v})} options={["Woman","Man","Nonbinary"]}/><div className="form-two"><label>City<input required maxLength={60} value={edit.city} onChange={e=>setEdit({...edit,city:e.target.value})}/></label><label>What you do<input maxLength={80} value={edit.job} onChange={e=>setEdit({...edit,job:e.target.value})}/></label></div><label>Looking for</label><Choice label="Relationship intention" value={edit.intent} onChange={(v:string)=>setEdit({...edit,intent:v})} options={["Long-term relationship","Open to exploring","Life partner"]}/><label>About you<textarea required minLength={10} maxLength={700} value={edit.bio} onChange={e=>setEdit({...edit,bio:e.target.value})}/></label><label>Interests · up to 8, separated by commas<input value={edit.interests} onChange={e=>setEdit({...edit,interests:e.target.value})}/></label><label>A conversation starter<textarea maxLength={400} placeholder="We'll get along if..." value={edit.prompt} onChange={e=>setEdit({...edit,prompt:e.target.value})}/></label><label className="switch-label">Pause discovery<Switch checked={edit.paused} onCheckedChange={v=>setEdit({...edit,paused:v})}/></label><p className="fine-print">Your profile and dating activity may appear in the connections and queues viewed by eligible matched members. Your birthday and chats are private.</p>{!me&&<label className="switch-label"><span>I am 18+ and agree to this profile and dating-activity visibility.</span><Switch checked={consent} onCheckedChange={setConsent}/></label>}<button className="primary" disabled={working||uploading||(!me&&!consent)}>{working?"Saving...":"Save my profile"}</button></form>}
 {modal==="date"&&active&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();if(!when)return;const next=await act("date",{matchId:active.id,venue,occurs:new Date(when).toISOString()});if(next){setModal("");setVenue("");setWhen("");toast.success("Invitation sent. They can accept or decline.");}}}><p>Invite {active.partner.name} to meet.</p><label>A public place<input required maxLength={160} placeholder="Coffee at..." value={venue} onChange={e=>setVenue(e.target.value)}/></label><label>Date and time<input required type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></label><p className="fine-print">Your local timezone: {Intl.DateTimeFormat().resolvedOptions().timeZone}. A plan becomes confirmed when both people agree.</p><button className="primary" disabled={working}>Send date invitation</button></form>}
 {modal==="connection-options"&&active&&<div className="form-stack"><button className="secondary" onClick={()=>{setModal("");setDetail(active.partner);}}>View profile</button><button className="secondary" onClick={()=>setConfirm({action:"unmatch",matchId:active.id,title:"End this connection?",description:"Your conversation will close and eligible queued likes may become new matches."})}>Unmatch</button><button className="danger-text" onClick={()=>{setDetail(active.partner);setModal("report");}}>Report & block</button></div>}
 {modal==="report"&&detail&&<div className="form-stack"><p>Report {detail.name}. This also blocks their profile and ends your connection.</p><Choice label="Reason" value={reason} onChange={setReason} options={["Inappropriate behavior","Fake profile","Harassment","Under 18","Other"]}/><label>Anything else we should know?<textarea maxLength={1200} value={report} onChange={e=>setReport(e.target.value)}/></label><p className="fine-print">Reports are saved. This preview does not have a staffed moderation team.</p><button className="primary" disabled={working} onClick={async()=>{const next=await act("report",{target:detail.id,reason,details:report});if(next){setModal("");setDetail(null);setReport("");toast.success("Report saved and profile blocked.");}}}>Submit report & block</button></div>}
 {modal==="transparency"&&active&&state?.plans.capacity&&<div className="transparency-list"><h3>Other current connections</h3>{state.transparency[active.partner.id]?.connections.length?state.transparency[active.partner.id].connections.map((p:any)=><div className="queue-row" key={p.id}><Avatar person={p}/><button className="row-person" onClick={()=>{setDetail({...p,readOnly:true});setModal("");}}><strong>{p.name}, {p.age}</strong><span>{p.city} · View profile</span></button><Clock3 size={17}/></div>):<p>No other visible active connections.</p>}<h3>Incoming queue · arrival order</h3>{state.transparency[active.partner.id]?.queue.length?state.transparency[active.partner.id].queue.map((p:any,i:number)=><div className="queue-row" key={p.id}><span className="row-position">#{i+1}</span><Avatar person={p}/><button className="row-person" onClick={()=>{setDetail({...p,readOnly:true});setModal("");}}><strong>{p.name}, {p.age}{p.id===me?.id?" (you)":""}</strong><span>{p.city} · View profile</span></button></div>):<p>No visible people waiting.</p>}<p className="fine-print">Read-only. Blocked profiles are omitted. Access ends when your connection or membership ends.</p></div>}
 </DialogContent></Dialog>
 <Sheet open={!!detail&&modal!=="report"} onOpenChange={open=>{if(!open)setDetail(null);}}><SheetContent className="profile-sheet"><SheetHeader><SheetTitle>{detail?.name}, {detail?.age}</SheetTitle><SheetDescription>{detail?.city} · {detail?.job}</SheetDescription></SheetHeader>{detail&&<div className="sheet-body">{detail.photos[0]&&<img className="sheet-photo" src={detail.photos[0]} alt={detail.name}/>}<div className="sheet-status">{detail.busy&&<span><Clock3 size={16}/>{detail.activeCount}/{detail.capacity} connected</span>}{detail.likesYou&&<span className="green"><Check size={17}/> Likes you</span>}<span>#{detail.queuePosition} in queue</span></div><span className="tag">{detail.intent}</span><h3>A little about me</h3><p>{detail.bio}</p><div className="interests">{detail.interests.map((t:string)=><span className="tag" key={t}>{t}</span>)}</div><blockquote>{detail.prompt}</blockquote>{detail.photos.slice(1).map((src:string)=><img className="sheet-photo" src={src} key={src} alt={"More of "+detail.name}/>)}{!detail.readOnly&&!full&&!detail.liked&&!state?.matches.some((m:any)=>m.partner.id===detail.id)&&<div className="button-row"><button className="secondary" disabled={working} onClick={()=>swipe("pass",detail)}>Pass</button><button className="primary" disabled={working} onClick={()=>swipe("like",detail)}><Heart size={17}/> Like {detail.name}</button></div>}<button className="text-button" onClick={()=>setModal("report")}><Flag size={16}/> Report & block</button><button className="danger-text" onClick={()=>setConfirm({action:"block",target:detail.id,title:"Block "+detail.name+"?",description:"You will no longer see each other, pending likes are removed, and your connection ends."})}>Block profile</button></div>}</SheetContent></Sheet>
 <AlertDialog open={!!confirm} onOpenChange={open=>{if(!open)setConfirm(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{confirm?.description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep as is</AlertDialogCancel><AlertDialogAction onClick={async()=>{if(!confirm)return;const result=await act(confirm.action,confirm);if(result){setDetail(null);setModal("");toast.success("Updated.");}}}>Confirm</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}

