export const demoPeople=[
 {key:"me",name:"Jamie",dob:"1997-06-12",gender:"Nonbinary",city:"Brooklyn, NY",job:"Product designer",bio:"Curious by default. Usually planning a weekend around a bookshop and a very good sandwich.",prompt:"A perfect Sunday is a slow morning, a new neighborhood, and nowhere to rush.",interests:["Coffee walks","Design","Live music"],photo:""},
 {key:"maya",name:"Maya",dob:"1998-04-17",gender:"Woman",city:"Brooklyn, NY",job:"Architect",bio:"Designing spaces by day, finding little adventures in between. I believe the best conversations happen on long walks with no particular destination.",prompt:"We'll get along if you have a favorite little coffee shop and a big curiosity about the world.",interests:["Coffee walks","Design","Weekend escapes"],photo:"16564600"},
 {key:"elena",name:"Elena",dob:"1996-02-24",gender:"Woman",city:"Brooklyn, NY",job:"Writer",bio:"One more chapter, one more song, one more reason to stay out a little longer.",prompt:"My simple pleasure: a sunny reading spot and an impossibly flaky croissant.",interests:["Books","Baking","Art"],photo:"33482275"},
 {key:"aria",name:"Aria",dob:"1999-01-14",gender:"Woman",city:"Manhattan, NY",job:"Creative producer",bio:"Big on small moments. Let's find a new restaurant and order something neither of us can pronounce.",prompt:"Together we could find the city's best dumplings. Serious research.",interests:["Food","Travel","Photography"],photo:"13205272"},
 {key:"noah",name:"Noah",dob:"1996-10-03",gender:"Man",city:"Queens, NY",job:"Music teacher",bio:"I make playlists for everything. Yes, including a trip to the grocery store.",prompt:"The way to win me over is to share a song that means something to you.",interests:["Live music","Hiking","Cooking"],photo:"37720662"},
 {key:"theo",name:"Theo",dob:"1994-11-20",gender:"Man",city:"Brooklyn, NY",job:"Photographer",bio:"Chasing good light and better company. Always up for a weekend outside the city.",prompt:"My ideal first date: a gallery, a good walk, and seeing where the conversation goes.",interests:["Photography","Art","Outdoors"],photo:"936090"}
];

