import { sqliteTable, text, integer, uniqueIndex, index } from "drizzle-orm/sqlite-core";
export const spaces=sqliteTable("spaces",{id:text("id").primaryKey()});
export const profiles=sqliteTable("profiles",{
 id:text("id").primaryKey(),scope:text("scope").notNull().references(()=>spaces.id,{onDelete:"cascade"}),
 name:text("name").notNull(),dob:text("dob").notNull(),gender:text("gender").notNull(),city:text("city").notNull(),job:text("job").notNull().default(""),
 bio:text("bio").notNull().default(""),intent:text("intent").notNull().default("Long-term relationship"),interests:text("interests").notNull().default("[]"),
 photos:text("photos").notNull().default("[]"),prompt:text("prompt").notNull().default(""),paused:integer("paused").notNull().default(0),created:integer("created").notNull()
},t=>[index("idx_profiles_scope").on(t.scope)]);
export const likes=sqliteTable("likes",{id:integer("id").primaryKey({autoIncrement:true}),sender:text("sender").notNull().references(()=>profiles.id,{onDelete:"cascade"}),recipient:text("recipient").notNull().references(()=>profiles.id,{onDelete:"cascade"})},t=>[uniqueIndex("idx_likes_pair").on(t.sender,t.recipient),index("idx_likes_recipient").on(t.recipient,t.id)]);
export const passes=sqliteTable("passes",{id:integer("id").primaryKey({autoIncrement:true}),sender:text("sender").notNull().references(()=>profiles.id,{onDelete:"cascade"}),recipient:text("recipient").notNull().references(()=>profiles.id,{onDelete:"cascade"})},t=>[uniqueIndex("idx_passes_pair").on(t.sender,t.recipient)]);
export const matches=sqliteTable("matches",{id:text("id").primaryKey(),a:text("a").notNull().references(()=>profiles.id,{onDelete:"cascade"}),b:text("b").notNull().references(()=>profiles.id,{onDelete:"cascade"}),started:integer("started").notNull(),ended:integer("ended"),operation:text("operation")},t=>[index("idx_matches_a").on(t.a,t.ended),index("idx_matches_b").on(t.b,t.ended)]);
export const blocks=sqliteTable("blocks",{id:integer("id").primaryKey({autoIncrement:true}),sender:text("sender").notNull().references(()=>profiles.id,{onDelete:"cascade"}),recipient:text("recipient").notNull().references(()=>profiles.id,{onDelete:"cascade"})},t=>[uniqueIndex("idx_blocks_pair").on(t.sender,t.recipient)]);
export const messages=sqliteTable("messages",{id:text("id").primaryKey(),matchId:text("match_id").notNull().references(()=>matches.id,{onDelete:"cascade"}),sender:text("sender").notNull(),body:text("body").notNull(),created:integer("created").notNull()},t=>[index("idx_messages_match").on(t.matchId,t.created)]);
export const dates=sqliteTable("dates",{id:text("id").primaryKey(),matchId:text("match_id").notNull().references(()=>matches.id,{onDelete:"cascade"}),sender:text("sender").notNull(),venue:text("venue").notNull(),occurs:text("occurs").notNull(),status:text("status").notNull().default("pending")},t=>[index("idx_dates_match").on(t.matchId)]);
export const reports=sqliteTable("reports",{id:text("id").primaryKey(),reporter:text("reporter").notNull(),target:text("target").notNull(),reason:text("reason").notNull(),details:text("details").notNull(),created:integer("created").notNull()});
export const requests=sqliteTable("requests",{id:text("id").primaryKey(),payload:text("payload").notNull(),created:integer("created").notNull()});
export const photos=sqliteTable("photos",{id:text("id").primaryKey(),owner:text("owner").notNull(),scope:text("scope").notNull(),mime:text("mime").notNull()});

export const plans=sqliteTable("plans",{id:text("id").primaryKey(),owner:text("owner").notNull(),addon:text("addon").notNull(),expires:integer("expires").notNull(),subscription:text("subscription"),customer:text("customer"),updated:integer("updated").notNull().default(0)},t=>[uniqueIndex("idx_plans_owner_addon").on(t.owner,t.addon)]);
export const billingEvents=sqliteTable("billing_events",{id:text("id").primaryKey(),created:integer("created").notNull()});

export const billingAccounts=sqliteTable("billing_accounts",{owner:text("owner").primaryKey(),customer:text("customer").notNull()});

export const cliqueSettings=sqliteTable("clique_settings",{owner:text("owner").primaryKey().references(()=>profiles.id,{onDelete:"cascade"}),enabled:integer("enabled").notNull().default(0),groupsEnabled:integer("groups_enabled").notNull().default(0),revision:integer("revision").notNull().default(0)});
export const friendships=sqliteTable("friendships",{id:text("id").primaryKey(),a:text("a").notNull().references(()=>profiles.id,{onDelete:"cascade"}),b:text("b").notNull().references(()=>profiles.id,{onDelete:"cascade"}),created:integer("created").notNull()},t=>[uniqueIndex("idx_friendship_pair").on(t.a,t.b)]);
export const friendLikes=sqliteTable("friend_likes",{id:integer("id").primaryKey({autoIncrement:true}),sender:text("sender").notNull().references(()=>profiles.id,{onDelete:"cascade"}),recipient:text("recipient").notNull().references(()=>profiles.id,{onDelete:"cascade"}),replacement:text("replacement"),created:integer("created").notNull()},t=>[uniqueIndex("idx_friend_like_pair").on(t.sender,t.recipient)]);
export const friendPasses=sqliteTable("friend_passes",{id:integer("id").primaryKey({autoIncrement:true}),sender:text("sender").notNull().references(()=>profiles.id,{onDelete:"cascade"}),recipient:text("recipient").notNull().references(()=>profiles.id,{onDelete:"cascade"})},t=>[uniqueIndex("idx_friend_pass_pair").on(t.sender,t.recipient)]);
export const groupLikes=sqliteTable("group_likes",{id:integer("id").primaryKey({autoIncrement:true}),sender:text("sender").notNull().references(()=>profiles.id,{onDelete:"cascade"}),recipient:text("recipient").notNull().references(()=>profiles.id,{onDelete:"cascade"}),senderRevision:integer("sender_revision").notNull(),recipientRevision:integer("recipient_revision").notNull()},t=>[uniqueIndex("idx_group_like_pair").on(t.sender,t.recipient)]);
export const groupMatches=sqliteTable("group_matches",{id:text("id").primaryKey(),a:text("a").notNull().references(()=>profiles.id,{onDelete:"cascade"}),b:text("b").notNull().references(()=>profiles.id,{onDelete:"cascade"}),size:integer("size").notNull(),created:integer("created").notNull()},t=>[uniqueIndex("idx_group_match_pair").on(t.a,t.b)]);
export const cliqueMessages=sqliteTable("clique_messages",{id:text("id").primaryKey(),friendship:text("friendship").references(()=>friendships.id,{onDelete:"cascade"}),groupMatch:text("group_match").references(()=>groupMatches.id,{onDelete:"cascade"}),sender:text("sender").notNull().references(()=>profiles.id,{onDelete:"cascade"}),body:text("body").notNull(),created:integer("created").notNull()});
export const cliqueSeeds=sqliteTable("clique_seeds",{scope:text("scope").primaryKey().references(()=>spaces.id,{onDelete:"cascade"})});
